# Generated by Django 3.2.7 on 2021-09-11 12:10

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210910_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile/default/default.apng', force_format=None, keep_meta=True, quality=99, size=[230, 230], upload_to='profile/%Y/%m/%d'),
        ),
    ]
