version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: bash -c "python3 djangojuniorproject/manage.py migrate && python3 djangojuniorproject/manage.py initadmin && python3 djangojuniorproject/manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy